services:
  solana:
    image: tchambard/solana-test-validator:latest
    container_name: solana-test-validator
    command: solana-test-validator --ledger /home/node/.config/solana/.ledger -r --bind-address 0.0.0.0 --rpc-port 8899
    ports:
      - "8899:8899"   # RPC
      - "8900:8900"   # Websocket
    volumes:
      - solana-docker:/opt
      - solana-docker-cache:/home/node/.cache
      - ./solana/ledger:/home/node/.config/solana/ledger
      - ./solana/cache:/home/node/.cache
      - ./solana/config:/home/node/.config/solana
      - .:/working_dir
    working_dir: /working_dir
  backend:
    build:
      context: .
      dockerfile: dockerfiles/backend.Dockerfile
    ports:
      - "3000:3000"
  frontend:
    build:
      context: .
      dockerfile: dockerfiles/frontend.Dockerfile
    ports:
      - "80:80"
  anchor:
    build:
      context: .
      dockerfile: dockerfiles/anchor.Dockerfile
    container_name: anchor-cli
    depends_on:
      - solana
    volumes:
      - ./solana/config:/root/.config/solana   # ключи и config.yml
      - .:/anchor
    working_dir: /anchor
    environment:
      - ANCHOR_WALLET=/root/.config/solana/id.json
      - ANCHOR_PROVIDER_URL=http://solana:8899


volumes:
  solana-docker:
  solana-docker-cache:
