services:
  backend:
    build:
      context: .
      dockerfile: dockerfiles/backend.Dockerfile
    ports:
      - "3000:3000"
  frontend:
    build:
      context: .
      dockerfile: dockerfiles/frontend.Dockerfile
    ports:
      - "80:80"
  anchor:
    build:
      context: .
      dockerfile: dockerfiles/anchor.Dockerfile
    container_name: anchor-cli
    volumes:
      - ./solana/config:/root/.config/solana   # ключи и config.yml
      - ./anchor:/anchor
    working_dir: /anchor
    environment:
      - ANCHOR_WALLET=/root/.config/solana/id.json
      - ANCHOR_PROVIDER_URL=https://api.devnet.solana.com

volumes:
  solana-docker:
  solana-docker-cache:
